### ISSUE TITLE
Unable to get single alarm object 

### ISSUE THREAD

**Issue by mubashardev** [tomergoldst/timekeeper#1]
I've used this dependency. Worked fine, but I was unable to get the specific **alarm object** which is triggered. How can I check that which of the alarm is received by Broadcast Receiver. I only gives the list of all alarms. 
I could be helpful if it returns the id of **received/triggered alarm.**

**Comment by tomergoldst** [comment]
Within the receiver you defined you can get the alarms for that alarm time from the intent in the following way:
```java
List<Alarm> alarms = intent.getParcelableArrayListExtra("alarms");
```
You get a list of alarms cause there might be more then one alarm for a particular time. After you have the list of relevant alarms you can iterate those alarms and use the method `getUid()` for each `Alarm` object. `UID` will be the id you provided when created the alarm.

See MyAlarmReceiver.java class at the demo app
